### ISSUE TITLE
Default currency

### ISSUE THREAD

**Issue by Photon-GitHub** [rodel77/SpigotSellsViewer-ChromeExtension#10]
Right now the default currency is always USD and cannot be changed via settings (at least via AddOn-Menu on Firefox).
I would appreciate a little default currency setting so I don't need to change it to my own country's currency on each page reload.

**Comment by rodel77** [comment]
Thanks for the suggestion i will search a method to do it with support in current supported browsers!

**Comment by rodel77** [comment]
Yes, it took 3 years to clear up this issue. Now we will have to wait for the update to finish and for chrome to accept it.
