### ISSUE TITLE
Firefox addons

### ISSUE THREAD

**Issue by Photon-GitHub** [rodel77/SpigotSellsViewer-ChromeExtension#11]
You should register the extension as an official resource in Firefox's addon hub
(https://addons.mozilla.org/de/firefox/)

**Comment by rodel77** [comment]
Yeah, i tried it but they ask me to change ton of things (Including stuff in libraries (Ajax, highcharts, etc)) currently i will continue doing it like that, if i create my own libs or found a solution i will try it again ;)
