### ISSUE TITLE
Decimals not calculated in large amounts and are decreased by one.

### ISSUE THREAD

**Issue by Photon-GitHub** [rodel77/SpigotSellsViewer-ChromeExtension#13]
You have two critical bugs in the graph data presentation: it simply neglects all decimals when multiplied.
Note: One sale is displayed correctly with decimals decreased by one cent, but beyond that single selling decimals are ignored.

Example from the graph (sale numbers are not real, but just a description of the problem):
I sell my resource AACAdditionPro for 11.99€
With one selling the graph tells me I made 11.98€ (first bug), the graph should tell me I made 11.99€
With 10 sales the graph should obviously tell me that I have earned 119.90€, but instead the graph tells me I have earned 110.00€.

**Comment by Photon-GitHub** [comment]
Note: The decremented decimals are not a new phenomenon, reserved for the current price tag, every price I have ever had is reduced by one cent in the graph.

**Comment by rodel77** [comment]
Sorry for the delayed answer, i will check it asap, if you are a developer remember that this is a collaborative open source project, you can help a lot by fixing those things (you seem smart ;) )

**Comment by rodel77** [comment]
I updated the exchange rates:

https://github.com/rodel77/SpigotSellsViewer-ChromeExtension/blob/9705e2c9e49e6dd21f242490c0153dc0de47acfa/money.js#L8

And it seems to work properly now, tell me if you are still with the issue

**Comment by Photon-GitHub** [comment]
Sorry for the delay... christmas and so on.
The latest version doesn't seem to work at all for me (firefox), thus I cannot verify the disappearing of the bug :/

**Comment by rodel77** [comment]
An what its not working, any error or something?

**Comment by Photon-GitHub** [comment]
It simply doesn't calculate anything at all or even displays the "graph" option.
Spigot is the same without the addon.
I redownloaded to make sure it isn't just a corrupted version.

**Comment by rodel77** [comment]
Check the console to see if there is any error

**Comment by Photon-GitHub** [comment]
Yes, basically Firefox throws a security exception that your addon is not allowed to modify the data of the website (buyers.js is flagged)

**Comment by Photon-GitHub** [comment]
With a bit more testing I could find this error as well:
![grafik](https://user-images.githubusercontent.com/22870297/34640287-25faf1b2-f2f0-11e7-9b77-905e557f49fe.png)

**Comment by rodel77** [comment]
Sorry for delay i am working on lot of sponge projects now, the error is here

https://github.com/rodel77/SpigotSellsViewer-ChromeExtension/blob/bbc0e8a3303bc98bbbd366b89a1c8e13a2a2ff5e/common/money.js#L38

I will try to find a solution

**Comment by rodel77** [comment]
Wops, i closed it

**Comment by rodel77** [comment]
Fixed! just an exclamation sign...
