### ISSUE TITLE
Stats not loading FIrefox Ubuntu 16

### ISSUE THREAD

**Issue by andrei1058** [rodel77/SpigotSellsViewer-ChromeExtension#14]
I've just installed the addon, I've restarted the web browser but it still doesn't load any data.
ss: https://screenshots.firefox.com/5s60a5trZLrBRML2/www.spigotmc.org

**Comment by rodel77** [comment]
Please i need browser console logs to fix it
In chrome you have to enable debug messages from console, idk in firefox but make sure that all message types are enabled

**Comment by Photon-GitHub** [comment]
@rodel77 That is exactly the bug I have been experiencing all the time.
See my posts in #13 .

**Comment by rodel77** [comment]
Fixed, just an exclamation sign...
