### ISSUE TITLE
How do you install this on firefox?

### ISSUE THREAD

**Issue by PeachesMLG** [rodel77/SpigotSellsViewer-ChromeExtension#19]
Im probs being dumb but is there a way to install this on firefox?

I tried doing:

    Go to about:debugging#addons
    Load temporal addon
    Select the manifest.json file
    Now you can reload the extension on the Reload link
But thats just for testing and its temperery so if you close firefox it wont be loaded and I dont want to do that every launch

**Comment by rodel77** [comment]
Try this: Go to [https://spigot.rodeldev.xyz/](https://spigot.rodeldev.xyz/), download the firefox version and just drag  & drop it into the browser

**Comment by PeachesMLG** [comment]
Oh, My bad. I was installing the .zip Thank you.

**Comment by PeachesMLG** [comment]
ok, sorry. as spigot changed their buyers page and stuff. how do i build an extension from the source code? as the latest one available to download is 1.4.8
