### ISSUE TITLE
How updates influence sales

### ISSUE THREAD

**Issue by kangarko** [rodel77/SpigotSellsViewer-ChromeExtension#25]
It would be sick to view (visually) how each plugin's release influenced the sales on the graph.

**Comment by kangarko** [comment]
@rodel77 year later, any update on this please ? ;)

**Comment by rodel77** [comment]
Sorry, had no time to update this project!

**Comment by kangarko** [comment]
Sure, what about for a donation? Would be really awesome to see "spikes" or trends regarding this.

**Comment by rodel77** [comment]
Sounds right. Can you please elaborate more on the feature? I don't fully understand what you want. What of all the graphs do you refer to in the first comment?

**Comment by kangarko** [comment]
Sure, I've shoot a quick 2min video on what I meant ;) 

https://www.loom.com/share/e187bcf72ec44a97bccd3cf9604bd15b

**Comment by rodel77** [comment]
Nice video! I understand the updates thing, I see has highcharts something to do it: https://www.highcharts.com/demo/annotations
But I don't understand why you want the monthly graph to zoom into week days when there's a daily graph on top of it.

**Comment by kangarko** [comment]
I understand, no problem! If it's not that difficult you can just use the daily graph for the 'events' instead.

**Comment by rodel77** [comment]
Ok, will see if I can finish today's work and do this tomorrow (or today's afternoon)!

**Comment by rodel77** [comment]
Done in e12a5cd1a734161ef8f7f4bb342acc4a93d5998d, I will try to address #10 before publishing the update, you can now try it as a uncompressed debug extension.

![chrome_5xQbVIt6KJ](https://user-images.githubusercontent.com/7594867/93422845-4e34c080-f87a-11ea-90c7-6204752f1628.png)

**Comment by kangarko** [comment]
Awesome, where can I donate please?

**Comment by kangarko** [comment]
<img width="912" alt="Skjermbilde 2020-09-17 kl  12 38 01" src="https://user-images.githubusercontent.com/1918426/93459848-a6071200-f8e2-11ea-9370-23bce46f93d8.png">

Hey there, sorry, I'm unable to see those version annotations & changing the currency renders the graph blank. Just downloaded your source.

Edit: Click on "List" does not do anything:
<img width="1323" alt="Skjermbilde 2020-09-17 kl  12 42 40" src="https://user-images.githubusercontent.com/1918426/93460318-507f3500-f8e3-11ea-85f1-9048faf2190f.png">

**Comment by rodel77** [comment]
I would need the console errors in order to fix the issue

________________________________
De: Matej Pacan <notifications@github.com>
Enviado: jueves, 17 de septiembre de 2020 5:39 a. m.
Para: rodel77/SpigotSalesGraph
Cc: rodel77; Mention
Asunto: Re: [rodel77/SpigotSalesGraph] How updates influence sales (#25)


[Skjermbilde 2020-09-17 kl  12 38 01]<https://user-images.githubusercontent.com/1918426/93459848-a6071200-f8e2-11ea-9370-23bce46f93d8.png>

Hey there, sorry, I'm unable to see those version annotations & changing the currency renders the graph blank.

**Comment by rodel77** [comment]
Oh, go it, it was a problem with saleless days option turned on, fixed in 19cba95! You can pull the commit and try it

**Comment by kangarko** [comment]
Awesome thank you so much! I'm absolutely certain this will help everyone using your plugin too!

Small thing -- can you make the option https://i.imgur.com/wECVTRF.png automatically hide the labels without reloading the page? When the graph is shown in full without zooming in, annotations become stacked up to an unreadable point: https://i.imgur.com/nKiCsqd.png

**Comment by kangarko** [comment]
Bug: When there's no sales, the annotation is not visible/not draggable: ![a](https://i.imgur.com/N11cjbN.png)

**Comment by kangarko** [comment]
One more bug: When changing currencies, graph is broken:

![a](https://i.imgur.com/1EXsioP.gif)

**Comment by rodel77** [comment]
Will check them, just noticed the second one is broken from e4dfc83 (EDIT: This one is fixed)

**Comment by rodel77** [comment]
Please try it again, I think everything is cleared

**Comment by kangarko** [comment]
Lovely, thanks so much ;)

**Comment by rodel77** [comment]
Glad to hear you liked it. I am accepting donations at this email: rodel1407 at yahoo dot com

**Comment by kangarko** [comment]
Thanks, sent!

**Comment by rodel77** [comment]
Nice! Thank you, it is very appretiated ;)

**Comment by rodel77** [comment]
Hey, just a quick update: The release is up and running, chrome now has these annoying review policies so it may take *weeks* until it appears updated on their store. For now, you can continue to use it as a decompressed or put the .crx (I don't know if there's any difference). I'll try to notify you if I get to know when the update's up!

**Comment by kangarko** [comment]
No worries, the extracted file works just fine!
