### ISSUE TITLE
Money over 1k results in Money to 1

### ISSUE THREAD

**Issue by YellowPhoenix18** [rodel77/SpigotSellsViewer-ChromeExtension#26]
When money for one month is over 1000€, the point in the graph moves to Money 1. The sales-graph seems not affected. Probably a bug with the graph itself

**Comment by ArcaniaxGit** [comment]
Can confirm

**Comment by rodel77** [comment]
Fixed on b4098d4d3073b165288db174614e63e9026a00c3 version 1.6.0
