### ISSUE TITLE
Download is corrupt on firefox

### ISSUE THREAD

**Issue by demengc** [rodel77/SpigotSellsViewer-ChromeExtension#31]
Firefox says the add-on is corrupt when downloading on firefox.

**Comment by rodel77** [comment]
Please try the last version `1.6.0` and tell me if it's still happening

**Comment by demengc** [comment]
Yes, 
![image](https://user-images.githubusercontent.com/43016355/82630279-3f861780-9bc0-11ea-9968-27d7d54b5884.png)

**Comment by rodel77** [comment]
Looks like there was a META-INF folder missing in the last version's xpi file, I've updated the file of the 1.6.0 release, I've already tested it and works well but tell me if it works for you!

**Comment by demengc** [comment]
Seems to work now :)
