### ISSUE TITLE
Total graph now showing up

### ISSUE THREAD

**Issue by kangarko** [rodel77/SpigotSellsViewer-ChromeExtension#33]
@rodel77 I am having a new plugin unapproved yet and it seems to have corrupted the total graph, that is no longer being shown at all:

![chrome_ksOJREhM6K](https://user-images.githubusercontent.com/1918426/99971965-3740ac00-2d9e-11eb-9ad6-794348c64005.png)

**Comment by kangarko** [comment]
Also July 2020 is showing in the year 2017:

![chrome_6VXYbTw0vS](https://user-images.githubusercontent.com/1918426/99972199-8686dc80-2d9e-11eb-90c2-4cc37a6aff62.png)

**Comment by rodel77** [comment]
Can you show me how do the unapproved resources look like on the author page? Maybe also if you can send the HTML of it. That way I can make it so they are skipped

**Comment by kangarko** [comment]
Here it is: https://pastebin.com/au1kxBCZ (set expiration to 1month)

You can just search for "moderated"

**Comment by kangarko** [comment]
Also the 2020 sales bug showing in 2017 year appears quite randomly, sometimes there are two 2020 months, sometimes one, sometimes none.

**Comment by rodel77** [comment]
Ok, I downloaded the file. This week will be a bit busy, but I'll try to fix the moderated resource thing as soon as I am free. The other bug is strange, I'll see if I can replicate it, maybe it is just caused by the moderated resource, maybe it just skipped the sorting after failed?

**Comment by kangarko** [comment]
Awesome thank you! Will test the new build when you have time and let you know :)

**Comment by rodel77** [comment]
I fixed the unapproved thing in the last tag!

**Comment by kangarko** [comment]
Thank you!
